version: '3.8'

services:
  backend:
    build:
      context: ./backend  # ← DETTA var problemet!
      dockerfile: Dockerfile
    container_name: cold-storage-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - /Volumes:/app/disks:ro  # Dina macOS volymer
    environment:
      - DB_PATH=/app/data/cold_storage.db
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend  # ← Och detta
      dockerfile: Dockerfile
    container_name: cold-storage-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src  # Hot reload
      - ./frontend/public:/app/public
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  cold_storage_data:
    driver: locale