version: '2'

services:
  backend:
    build: ./backend
    container_name: cold-storage-backend
    user: "33:33"
    restart: "no"
    volumes:
      - ./data:/app/data
      - /mnt/storage:/app/disks:ro
    environment:
      - DB_PATH=/app/data/cold_storage.db
      - PYTHONPATH=/app
    expose:
      - "8000"
    # Lägg till denna för att hantera permissions automatiskt
    command: >
      sh -c "
        chown -R 33:33 /app/data || true &&
        python -m uvicorn main:app --host 0.0.0.0 --port 8000
      "
    networks:
      - webproxy

  frontend:
    # Använd färdig image (laddad från tar-fil)
    image: cold-storage-frontend:latest
    container_name: cold-storage-frontend
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - webproxy

networks:
  webproxy:
    external: true