version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cold-storage-backend
    ports:
      - "0.0.0.0:8000:8000"  # VIKTIGT: Lyssna på alla interfaces
    volumes:
      - ./data:/app/data
      - /Volumes:/app/disks:ro
    environment:
      - DB_PATH=/app/data/cold_storage.db
      - PYTHONPATH=/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cold-storage-frontend
    ports:
      - "0.0.0.0:3000:3000"  # VIKTIGT: Lyssna på alla interfaces
    environment:
      # INGEN statisk API URL - låt JavaScript detektera automatiskt
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    restart: unless-stopped