services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cold-storage-backend
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /mnt/storage:/app/disks:ro  # Justera efter din server
    environment:
      - DB_PATH=/app/data/cold_storage.db
      - PYTHONPATH=/app
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: cold-storage-frontend
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "80"
    depends_on:
      - backend

networks:
  default:
    external:
      name: webproxy

volumes:
  cold_storage_data:
    driver: local