version: '2'

services:
  backend:
    build: ./backend
    container_name: cold-storage-backend
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /mnt/storage:/app/disks:ro
    environment:
      DB_PATH: /app/data/cold_storage.db
      PYTHONPATH: /app
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: cold-storage-frontend
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - "80"
    depends_on:
      - backend

networks:
  default:
    external:
      name: webproxy